<script lang="ts">
    import { searchFilters } from "../mainStore";
    import DropdownChip from "./DropdownChip.svelte";

    const depts = {
        "ANTH": "Anthropology",
        "APLX": "Applied Linguistics",
        "AM": "Applied Mathematics",
        "ARBC": "Arabic",
        "ART": "Art",
        "ARTG": "Art&Des:Games&PlayableMedia",
        "ASTR": "Astronomy and Astrophysics",
        "BIOC": "Biochemistry and Molecular Bio",
        "BIOL": "Biology: Molecular Cell & Dev",
        "BIOE": "Biology:Ecology & Evolutionary",
        "BME": "Biomolecular Engineering",
        "CRSN": "Carson College",
        "CHEM": "Chemistry and Biochemistry",
        "CHIN": "Chinese",
        "CSP": "Coastal Science and Policy",
        "CLNI": "College Nine",
        "CMMU": "Community Studies",
        "CMPM": "Computational Media",
        "CSE": "Computer Science & Engineering",
        "COWL": "Cowell College",
        "CRES": "Critical Race & Ethnic Studies",
        "CRWN": "Crown College",
        "DANM": "Digital Arts and New Media",
        "EART": "Earth Sciences",
        "ECON": "Economics",
        "EDUC": "Education",
        "ECE": "Electrical & Computer Engineer",
        "ESCI": "Environmental Sciences",
        "ENVS": "Environmental Studies",
        "FMST": "Feminist Studies",
        "FILM": "Film and Digital Media",
        "FREN": "French",
        "GAME": "Games and Playable Media",
        "GERM": "German",
        "GCH": "Global and Community Health",
        "GRAD": "Graduate",
        "GREE": "Greek",
        "HEBR": "Hebrew",
        "HIS": "History",
        "HAVC": "History of Art&Visual Culture",
        "HISC": "History of Consciousness",
        "HCI": "Human Computer Interaction",
        "HUMN": "Humanities",
        "ITAL": "Italian",
        "JAPN": "Japanese",
        "JRLC": "John R. Lewis College",
        "KRSG": "Kresge College",
        "LAAD": "Languages",
        "LATN": "Latin",
        "LALS": "Latin American&Latino Studies",
        "LGST": "Legal Studies",
        "LING": "Linguistics",
        "LIT": "Literature",
        "MATH": "Mathematics",
        "MERR": "Merrill College",
        "METX": "Microbiol & Environ Toxicology",
        "MUSC": "Music",
        "NLP": "Natural Language Processing",
        "OAKS": "Oakes College",
        "OCEA": "Ocean Sciences",
        "PERS": "Persian",
        "PHIL": "Philosophy",
        "PBS": "Physical & Biological Sciences",
        "PHYE": "Physical Education",
        "PHYS": "Physics",
        "POLI": "Politics",
        "PRTR": "Porter College",
        "PORT": "Portuguese",
        "PSYC": "Psychology",
        "SCIC": "Science Communication",
        "SOCD": "Social Documentation",
        "SOCY": "Sociology",
        "SPAN": "Spanish",
        "SPHS": "Spanish for Heritage Speakers",
        "STAT": "Statistics",
        "STEV": "Stevenson College",
        "TIM": "Technology & Info Management",
        "THEA": "Theater Arts",
        "UCDC": "UCDC",
        "VAST": "Visualizing Abolition Studies",
        "WRIT": "Writing"
    }
</script>

<DropdownChip multiple={true} bind:value={$searchFilters.department} label="Dept" options={depts} />